language: python
dist: bionic
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install tox
script:
  - tox
matrix:
  include:
    - python: "3.10"
      env: TOXENV=py36
    - python: "3.10"
      env: TOXENV=linting
notifications:
  email: false
